table gap_dropout_male
	lineageTag: 0b03bdb3-ba77-4d22-8baf-528fc1f90ca5

	column iso3c
		dataType: string
		lineageTag: 1f3bda2c-f368-44cd-8f08-915f564ae75a
		summarizeBy: none
		sourceColumn: iso3c

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: bd3ee81b-828c-4080-a945-8eace1e5b464
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column unicef_region
		dataType: string
		lineageTag: 44223803-305a-46e4-a5d8-420a2f6e0b17
		summarizeBy: none
		sourceColumn: unicef_region

		annotation SummarizationSetBy = Automatic

	column region_name
		dataType: string
		lineageTag: 12ca2628-1429-452f-bec5-d2c365469b1a
		summarizeBy: none
		sourceColumn: region_name

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: ad42d938-0d0c-460a-a1f6-9cfb2c745a99
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column metric
		dataType: string
		lineageTag: 137b5777-c7c0-45de-a949-14eaa778966c
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column sex
		dataType: string
		lineageTag: 4fe56586-f383-4a16-9bc0-fc4fb49cac31
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column coverage_dose1
		dataType: int64
		formatString: 0
		lineageTag: 9bfa15ce-ff1d-4455-8c98-3a4553891fbd
		summarizeBy: sum
		sourceColumn: coverage_dose1

		annotation SummarizationSetBy = Automatic

	column coverage_complete
		dataType: int64
		formatString: 0
		lineageTag: 2b0736ae-d04b-47e0-a1e9-d59eecc20232
		summarizeBy: sum
		sourceColumn: coverage_complete

		annotation SummarizationSetBy = Automatic

	column dropout
		dataType: int64
		formatString: 0
		lineageTag: 27aed039-2d03-4594-a9d7-6243a6be73fe
		summarizeBy: sum
		sourceColumn: dropout

		annotation SummarizationSetBy = Automatic

	partition gap_dropout_male = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Pc\Desktop\CURSOS\PYTHON\hpv_dashboard\powerbi_data\hpv_powerbi_tables.xlsx"), null, true),
				    gap_dropout_male_Sheet = Origen{[Item="gap_dropout_male",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(gap_dropout_male_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"iso3c", type text}, {"country", type text}, {"unicef_region", type text}, {"region_name", type text}, {"year", Int64.Type}, {"metric", type text}, {"sex", type text}, {"coverage_dose1", Int64.Type}, {"coverage_complete", Int64.Type}, {"dropout", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

